CREATE DATABASE IF NOT EXISTS autenticacao_jwt;
  

USE autenticacao_jwt;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT  AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(100) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
